### ISSUE TITLE
ConsenSys Grants Challenge @ EthBoston 

### ISSUE THREAD

**Issue by datakarima** [Consensys/CosnenSys-Grants-#2]
# ConsenSys Grants Challenge  
---------------------------------------------------------------------------------------------------

ConsenSys Grants funds projects that meet the needs of a rapidly accelerating Ethereum ecosystem. Learn more about ConsenSys grants at grants.consensys.net. ConsenSys Grants is awarding 1 award to the best projects of the following 5 categories. 

**Social Impact Challenge** -Ethereum has the infrastructure built to tackle pressing social issues. Leveraging the power of Ethereum, create a solution that enables the betterment of society and/or democratizes public access to resources.

**Infrastructure Challenge (L1 & L2) Challenge** - In order for Ethereum to be utilized by billions of people, critical infrastructure (i.e., scaling solutions) still needs to be built out. Come up with a solution that will help improve the scalability, privacy, or interoperability of Ethereum.

**Security Challenge** - Altering published smart contracts is impossible because blockchains are immutable. As a result, attackers prey on smart contracts with vulnerabilities. Create a solution that improves the developer experience with security on Ethereum.

**Usability and Dev Tooling Challenge** -Continue to support the Ethereum developer ecosystem and enhanced user experiences by building a tool that will improve developer kits and create friendlier user experiences. Overall our goal is to find projects that continue to support the Ethereum developer ecosystem and enhance user experiences.

**Education & Technical Knowledge Challenge**- Help improve the on-boarding experience of new and existing developers through tutorials or educational tools for developing with the Web3 Stack.

## How to qualify

[ ] Projects must benefit the wider ethereum ecosystem rather than one single entity.
[ ] Projects that ship software must eventually be open-sourced under a suitable OSI approved license and must have a collaborative community governance model or a well-defined path to implementing one.
[ ] Project will disqualify if a ConsenSys employee is on their team or they have previously received funding from ConsenSys

 
## Resources

[Take a look at our current grantees](https://www.grants.consensys.net/meet-our-grantees) 
[Past ConsenSys Grants Hackathon Winners](https://github.com/ConsenSys/CosnenSys-Grants-/wiki/ConsenSys-Grants-Hackathon-Winners) 

## Judging Criteria

1\.Project has sustainable life-cycle (i.e. can scale) and utilizes a well-established open source community supported framework and has multi-platform support
2\. Team must show long term commitment in building out and seeing their project to completion. 
3\.The project has not been implemented before and solves the problem presented and provides a good solution

## Prizes

1\. 1000 DAI
2\.  If winning team choices to apply for a grant their application would be fast tracked past 2 of 4  evaluation rounds.

**Comment by holle197** [comment]
https://github.com/holle197/Solidity-Wallet/blob/master/Wallet.sol

https://etherscan.io/address/0x94faa69a60a4cb460e9455fa0d312bbe6a2882ea
